version: "3"
services:
    mk-home-server:
        build: .
        container_name: mkhs
        networks:
            - mk_home_backend
        ports:
            - 8000:8000
            - 5353:5353
            - 5684:5684
            - 51379:51379
networks:
    mk_home_backend:
